### ISSUE TITLE
README instruction

### ISSUE THREAD

**Issue by maithuy** [matrix-org/matrix-react-skin#2]
1. Install or update node.js so that your npm is at least at version 2.0.0
2. Clone the repo: git clone https://github.com/matrix-org/matrix-react-skin.git
3. Switch to the SDK directory: cd matrix-react-sdk
4. Install the prerequisites: npm install
5. Build the example and start a server: npm start

Did you mean go to the matrix-react-skin directory in step 3? If yes, it has error (please see below)

> parallelshell 'npm run start:js' 'npm run start:skins:css' 'http-server -c 1'

child_process.js:420
    throw new ERR_INVALID_ARG_TYPE('options.cwd', 'string', options.cwd);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options.cwd" property must be of type string. Received type function
    at normalizeSpawnArguments (child_process.js:420:11)
    at spawn (child_process.js:522:38)
    at /Users/thuynguyen/Development/riot-im/matrix-react-skin/node_modules/parallelshell/index.js:104:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/thuynguyen/Development/riot-im/matrix-react-skin/node_modules/parallelshell/index.js:100:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! matrix-react-skin@0.0.2 start: `parallelshell 'npm run start:js' 'npm run start:skins:css' 'http-server -c 1'`
npm ERR! Exit status 1

**Comment by tubbo** [comment]
same. i think this project is dead.
